theme: jekyll-theme-cayman
title: My Digital Humanities Capstone Project
description: A site to display my Tableau visualizations from my DH capstone project analyzing British parliamentary debates through text analysis.
