theme: jekyll-theme-cayman
title: A Text Analysis of British Welfare Debates
description: A site to display Tableau visualizations from my DH capstone project analyzing British parliamentary debates through text analysis.
